name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install NDK
      run: |
        sdkmanager --install "ndk;25.2.9519653"
        sdkmanager --install "cmake;3.22.1"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create dummy API_KEYS file
      run: |
        echo "APP_ID=\"123456\"" > API_KEYS
        echo "APP_HASH=\"abcdef123456\"" >> API_KEYS
        echo "MAPS_V2_API=\"dummy-maps-key\"" >> API_KEYS
        echo "SIGNING_KEY_STORE_PASSWORD=\"dummy\"" >> API_KEYS
        echo "SIGNING_KEY_ALIAS=\"dummy\"" >> API_KEYS
        echo "SIGNING_KEY_PASSWORD=\"dummy\"" >> API_KEYS

    - name: Build arm64 Debug APK
      run: ./gradlew :TMessagesProj:assembleArm64Debug

    - name: Build armv7 Debug APK
      run: ./gradlew :TMessagesProj:assembleArmv7Debug

    - name: Upload Debug APKs
      uses: actions/upload-artifact@v4
      with:
        name: apks
        path: |
          TMessagesProj/build/outputs/apk/arm64/debug/*.apk
          TMessagesProj/build/outputs/apk/armv7/debug/*.apk
